### ISSUE TITLE
pfo folder - data deletion

### ISSUE THREAD

**Issue by VIKASKENDRE** [jhult/pfmkit#2]
Hi Joe,

Hope you are well.

You have done an incredible job by creating this incredible application, pismo file mount, truly grateful for it. I have been using the pfo folder for quite some time now. But recently I noticed that whenever I delete any file/folder from it, even though it gets deleted, it doesn't clear up space from the drive i have stored the pfo in. For example, if the current data size of pfo is 2 gb and I delete 1 gb of data from it, it still occupies 2 gb of space on my storage device.

I hope I am not doing anything wrong, is there a specific process to delete data from pfo? If so it will be great if you can help me with thi
![pfo1](https://user-images.githubusercontent.com/30403300/135011161-4950155a-f1b9-4af8-af5a-e3dd7749daaa.PNG)
![pfo2](https://user-images.githubusercontent.com/30403300/135011178-81365af9-a53e-4af8-a10f-60ebd7e356b2.PNG)
s.

**Comment by jhult** [comment]
@VIKASKENDRE, I am not the developer of this. You will need to contact Pismo: https://pismotec.com/support/
